.TH "libosip" "1" 
.SH "NAME" 
libosip2 \(em The GNU oSIP library is a low layer SIP implementation. 
 
.SH "SYNOPSIS" 
.PP 
\fB#include <include/osipparser2/osip_const.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_md5.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_list.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_uri.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_message.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_port.h>\fR 
.PP 
\fB#include <include/osipparser2/sdp_message.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_headers.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_body.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_rfc3264.h>\fR 
.PP 
\fB#include <include/osipparser2/osip_parser.h>\fR 
.PP 
\fB-losipparser2\fR [\fBThe uri, SIP and SDP parsers\fP]  
.PP 
\fB#include <include/osip2/osip.h>\fR 
.PP 
\fB#include <include/osip2/osip_fifo.h>\fR 
.PP 
\fB#include <include/osip2/osip_dialog.h>\fR 
.PP 
\fB#include <include/osip2/osip_mt.h>\fR 
.PP 
\fB#include <include/osip2/osip_condv.h>\fR 
.PP 
\fB#include <include/osip2/osip_negotiation.h>  //OBSOLETE\fR 
.PP 
\fB-losip2\fR [\fBThe SIP transaction and the dialog API\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBlibosip2\fR library. 
.SH "API and Reference Documentation" 
.PP 
API reference & Doxygen documentation is available for 
osip at http://www.gnu.org/software/osip/ 
.SH "osip general overview." 
.PP 
The file help/man/osip.html in the source distribution 
should give you a nice amount of informations about the 
osip stack. 
.SH "Free software projects \-send me your project name-" 
.PP 
antisip, linphone, bayonne 
.SH "BUGS" 
.PP 
Please use the mailing list osip-dev@gnu.org 
.SH "AUTHOR" 
.PP 
This manual page was written by Aymeric Moizard amoizard at antisip.com. 
.\" created by instant / docbook-to-man, Fri 29 Jan 2016, 18:02 
